export const ErrorCodes = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQ_OVERLAP: 'REQ_OVERLAP',
  AUTH_EXISTS: 'AUTH_EXISTS',
  AUTH_NOT_ACTIVATED: 'AUTH_NOT_ACTIVATED',
  AUTH_DOESNT_EXIST: 'AUTH_DOESNT_EXIST',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED'
}
